baseURL = "http://jeremyber.com/"
languageCode = "en-us"
title = "Jeremy Ber"
theme = "minimal"
googleAnalytics = ""

[params]
    author = "Jeremy Ber"
    description = "Aspiring Rock Star, Film Director, Writer, Programmer, Movie Critic, Center for the Utah Jazz."
    githubUsername = "jeremyber"
    accent = "maroon"
    showBorder = true
    backgroundColor = "white"
    font = "Poppins" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "default"
    highlightLanguages = ["go", "haskell", "kotlin", "scala", "swift"]

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/about/"
    name = "About"
    weight = 2

[[menu.main]]
    url = "/post/"
    name = "Posts"
    weight = 3

[[menu.main]]
    url = "/project/"
    name = "Projects"
    weight = 4

# Social icons to be shown on the right-hand side of the navigation bar.
# The "name" field should match the name of the icon in Font Awesome.
# The list of available icons can be found at http://fontawesome.io/icons.

[[menu.icon]]
    url = "mailto:jeremydber@gmail.com"
    name = "fas fa-envelope"
    weight = 1

[[menu.icon]]
    url = "https://github.com/jeremyber/"
    name = "fab fa-github"
    weight = 2

[[menu.icon]]
    url = "https://twitter.com/jeremyataws/"
    name = "fab fa-twitter"
    weight = 3

[[menu.icon]]
    url = "https://www.linkedin.com/in/jeremyber/"
    name = "fab fa-linkedin"
    weight = 4
